### ISSUE TITLE
请问是不是豆瓣api用不了了

### ISSUE THREAD

**Issue by ChlorineLv** [Tencent-CloudEDU/WXCloud-bookcase#4]
直接在网址栏输入`http://api.douban.com/v2/book/isbn/9787559803306`
结果返回`{"msg":"invalid_request_scheme: http","code":100,"request":"GET \/v2\/book\/isbn\/9787559803306"}`
想请问是否api用不了了现在。

**Comment by poyiding** [comment]
> 直接在网址栏输入`http://api.douban.com/v2/book/isbn/9787559803306`
> 结果返回`{"msg":"invalid_request_scheme: http","code":100,"request":"GET \/v2\/book\/isbn\/9787559803306"}`
> 想请问是否api用不了了现在。

是的，豆瓣这个月把api 关了

**Comment by ChlorineLv** [comment]
> > 直接在网址栏输入`http://api.douban.com/v2/book/isbn/9787559803306`
> > 结果返回`{"msg":"invalid_request_scheme: http","code":100,"request":"GET \/v2\/book\/isbn\/9787559803306"}`
> > 想请问是否api用不了了现在。
> 
> 是的，豆瓣这个月把api 关了

噢，好的，谢谢啦
